steps:
  # 1️⃣ Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$SHORT_SHA',
      '.'
    ]

  # 2️⃣ Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$SHORT_SHA'
    ]

  # 3️⃣ Deploy to Cloud Run (with Cloud SQL + secrets + env vars)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', '$_SERVICE_NAME',
      '--image', '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$SHORT_SHA',
      '--region', '$_DEPLOY_REGION',
      '--platform', '$_PLATFORM',
      '--allow-unauthenticated',

      '--add-cloudsql-instances', 'khanabot:us-central1:mbbeats-mysql',

      # Secrets (must be ONE LINE)
      '--set-secrets=dialogflow-key=dialogflow-key:latest,DB_USER=db-user:latest,DB_PASS=db-pass:latest',

      # Env vars (must be ONE LINE)
      '--set-env-vars=PROJECT_ID=khanabot,DB_NAME=mb_eats,INSTANCE_CONNECTION_NAME=khanabot:us-central1:mbbeats-mysql'
    ]


images:
  - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$SHORT_SHA'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 200
  logging: CLOUD_LOGGING_ONLY

  # cache Docker layers
env:
  - DOCKER_BUILDKIT=1





