steps:
  # Step 1: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "-t", "us-central1-docker.pkg.dev/khanabot/mbeats-backend/mbeats-backend:$SHORT_SHA",
      "."
    ]

  # Step 2: Push the image
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "push",
      "us-central1-docker.pkg.dev/khanabot/mbeats-backend/mbeats-backend:$SHORT_SHA"
    ]

  # Step 3: Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: [
      "run", "deploy", "mbeats-backend",
      "--image=us-central1-docker.pkg.dev/khanabot/mbeats-backend/mbeats-backend:$SHORT_SHA",
      "--region=us-central1",
      "--platform=managed",
      "--allow-unauthenticated",
      "--add-cloudsql-instances=khanabot:us-central1:mbbeats-mysql",
      "--set-secrets=dialogflow-key=dialogflow-key:latest",
      "--set-env-vars=PROJECT_ID=khanabot,DB_USER=chatbot_user,DB_PASS=Msql$SecureCloud8848,DB_NAME=mb_eats,INSTANCE_CONNECTION_NAME=khanabot:us-central1:mbbeats-mysql"
    ]

images:
  - "us-central1-docker.pkg.dev/khanabot/mbeats-backend/mbeats-backend:$SHORT_SHA"
